{
    "openapi": "3.0.0",
    "info": {
        "version": "1.0.0",
        "title": "Identity Managment  CRUD",
        "description": "Identity Managment Application API"
    },

    "servers": [
        {
            "url": "http://localhost:5000/idm/api",
            "description": "Local server"
        }
    ],

    "tags": [
        {
            "name": "Enterprises",
            "description": "API for enterprise in the system"
        }
    ],
    "paths": {
        "/permissions": {
            "get": {
                "tag": ["Enterprises"],
                "summary": "Get all permission in the system",
                "responses": {
                    "200": {
                        "description": "get all permissions",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/permissionArray"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },
                    "400": {
                        "description": "Bad request. Request body must be json and parameterId must be arry of integer"
                    },
                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/permissions/search": {
            "get": {
                "tag": ["Enterprises"],
                "summary": "get all permissions for specific feature",
                "parameters": [
                    {
                        "in": "query",
                        "name": "feature",
                        "type": "string",
                        "description": " feature name "
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "text/plain": {
                                "schema": {
                                    "$ref": "#/components/responses/permissionArray"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/roles": {
            "post": {
                "tag": ["Enterprises"],
                "summary": "create role with permissions ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/createRole"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "role created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            },
            "get": {
                "tag": ["Enterprises"],
                "summary": "get all roles in the system",
                "responses": {
                    "200": {
                        "description": "get all roles successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/roleArray"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },
                    "400": {
                        "description": "Bad request. Request body must be json and parameterId must be arry of integer"
                    },
                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/roles/{id}": {
            "get": {
                "tag": ["Enterprises"],
                "summary": "get specifc role with permission by feature",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "role id"
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/roleWithPermissionObject"
                                }
                            }
                        }
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/notFound"
                                }
                            }
                        }
                    }
                }
            },
            "put": {
                "tag": ["Enterprises"],
                "summary": "update role with given permissions ",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "role id "
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/createRole"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "role created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 201,
                                    "message": "Role updated successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            },
            "delete": {
                "tag": ["Enterprises"],
                "summary": "delete role  ",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "role id "
                    }
                ],

                "responses": {
                    "200": {
                        "description": "role deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "Role deleted successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/users/list": {
            "get": {
                "tag": ["Enterprises"],
                "summary": "get all users",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/userListResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/notFound"
                                },
                                "example": {
                                    "code": "GET_USER_FAILED",
                                    "message": "Unable to get user failed",
                                    "httpCode": 500
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "tag": ["Enterprises"],
                "summary": "create user with permission ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/createUser"
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "user created successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 201,
                                    "message": "User created successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "delete": {
                "tag": ["Enterprises"],
                "summary": "delete user  ",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "user id "
                    }
                ],

                "responses": {
                    "200": {
                        "description": "user deleted successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "User deleted successfully.",
                                    "applicationErrorCode": 1114
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/users/suspend/{id}": {
            "put": {
                "tag": ["Enterprises"],
                "summary": "suspend user sucessfully",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "user id "
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user suspended successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "User suspended successfully.",
                                    "applicationErrorCode": 1114
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/users/activate/{id}": {
            "put": {
                "tag": ["Enterprises"],
                "summary": "activate user sucessfully",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "user id "
                    }
                ],
                "responses": {
                    "200": {
                        "description": "user activated successfully",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "User activated successfully.",
                                    "applicationErrorCode": 1114
                                }
                            }
                        }
                    },
                    "401": {
                        "description": " Authorization information is missing or invalid."
                    },

                    "500": {
                        "description": "Unexpected error. Internal server error."
                    }
                }
            }
        },
        "/enterprises/root": {
            "post": {
                "tag": ["Enterprises"],
                "summary": "create root enterprise ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/createEnterprise"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 201,
                                    "message": "Enterprise created successfully.",
                                    "enterpriseCode": "TY6Z-4TAH-W5X7",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/enterprises": {
            "get": {
                "tag": ["Enterprises"],
                "summary": "get enterprise details ",
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/getEnterpriseDetails"
                                }
                            }
                        }
                    }
                }
            },
            "post": {
                "tag": ["Enterprises"],
                "summary": "create root enterprise ",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/createEnterprise"
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 201,
                                    "message": "Enterprise created successfully.",
                                    "enterpriseCode": "TY6Z-4TAH-W5X7",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/enterprises/{id}/suspend": {
            "put": {
                "tag": ["Enterprises"],
                "summary": "suspent enterprise",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "enterprise id "
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "Enterprise suspended successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/enterprises/{id}/activate": {
            "put": {
                "tag": ["Enterprises"],
                "summary": "suspent enterprise",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "enterprise id "
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "Enterprise activated successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        },
        "/enterprises/{id}/delete": {
            "put": {
                "tag": ["Enterprises"],
                "summary": "delete enterprise",
                "parameters": [
                    {
                        "in": "path",
                        "name": "id",
                        "type": "integer",
                        "description": "enterprise id "
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/responses/createRoleResponse"
                                },
                                "example": {
                                    "code": 200,
                                    "message": "Enterprise deleted successfully.",
                                    "applicationErrorCode": 0
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "createRole": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "name of role "
                    },
                    "description": {
                        "type": "string"
                    },

                    "enterpriseCode": {
                        "type": "string"
                    },
                    "permissionId": {
                        "type": "array",
                        "items": {
                            "type": "integer"
                        },
                        "description": "permissions to that role"
                    }
                },
                "example": {
                    "name": "BA Entities Role",
                    "description": "Roles for CRUD Operations",
                    "enterpriseCode": "79622596-fc6a-4048-b0b6-ae40388fef8f",
                    "permissionId": [1, 2, 3]
                }
            },
            "createEnterprise": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "object",
                        "properties": {
                            "emailId": { "type": "string" },
                            "name": {
                                "type": "string"
                            },
                            "username": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "name": "happiestminds",
                    "admin": {
                        "emailId": "hm.bng@happiestminds.com",
                        "name": "happiestminds",
                        "username": "happiestminds-admin"
                    }
                }
            },
            "createUser": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "username": {
                        "type": "string"
                    },
                    "emailId": {
                        "type": "string"
                    },
                    "enterpriseCode": {
                        "type": "string"
                    },
                    "roles": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "example": {
                    "name": "HMT",
                    "username": "HMT-ORG",
                    "emailId": "abc.xyz@happiestminds.com",
                    "enterpriseCode": "79622596-fc6a-4048-b0b6-ae40388fef8f",
                    "roles": ["ADMIN", "DPO"]
                }
            }
        },
        "responses": {
            "createRoleResponse": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "integer",
                        "description": "status code "
                    },
                    "message": {
                        "type": "string",
                        "description": "sucess message from response"
                    },
                    "applicationErrorCode": {
                        "type": "integer"
                    }
                },
                "example": {
                    "code": 201,
                    "message": "Role created successfully.",
                    "applicationErrorCode": 0
                }
            },
            "permissionArray": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        }
                    }
                },
                "example": {
                    "User": [
                        {
                            "id": 1,
                            "name": "user_add",
                            "description": "add user",
                            "status": "A"
                        }
                    ]
                }
            },
            "userListResponse": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "username": {
                            "type": "string"
                        },
                        "emailId": {
                            "type": "string"
                        },
                        "enterpriseCode": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "userType": {
                            "type": "integer"
                        },
                        "roleNames": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "permissionsNames": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        },
                        "roles": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "status": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "example": {
                    "users": [
                        {
                            "id": 1,
                            "username": "HM-Org",
                            "name": "Hm-org",
                            "emailId": "manjunath.hindupur@happiestminds.com",
                            "enterpriseCode": "79622596-fc6a-4048-b0b6-ae40388fef8f",
                            "status": "A",
                            "userType": 1,
                            "roleNames": [
                                "PL Delete Model",
                                "PL User",
                                "PL Export",
                                "PL Assessment Template Co-ordinator",
                                "Admin"
                            ],
                            "permissionNames": [
                                "resource_fetch",
                                "user_delete"
                            ],
                            "roles": [
                                {
                                    "id": 611,
                                    "name": "PL User",
                                    "status": "A"
                                },
                                {
                                    "id": 622,
                                    "name": "PL Assessment Approver",
                                    "status": "A"
                                }
                            ]
                        }
                    ]
                }
            },
            "roleArray": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "permissions": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "id": {
                                        "type": "integer"
                                    },
                                    "name": {
                                        "type": "string"
                                    },
                                    "description": {
                                        "type": "string"
                                    },
                                    "status": {
                                        "type": "string"
                                    }
                                }
                            }
                        }
                    }
                },
                "example": {
                    "roles": [
                        {
                            "id": 1,
                            "name": "BA Entities Role",
                            "description": "Roles for CRUD Operations",
                            "status": "A",
                            "permissions": [
                                {
                                    "id": 20,
                                    "name": "resource_add",
                                    "description": "Add Resource",
                                    "status": "A"
                                }
                            ]
                        }
                    ]
                }
            },
            "roleWithPermissionObject": {
                "type": "object",
                "properties": {
                    "role_id": {
                        "type": "integer"
                    },
                    "name": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "permissionByFeature": {
                        "type": "object",
                        "schema": {
                            "$ref": "#/components/responses/permissionArray"
                        }
                    }
                },
                "example": {
                    "id": 1,
                    "name": "BA Entities Role",
                    "description": "Roles for CRUD Operations",
                    "status": "A",
                    "permissionByFeature": {
                        "User": [
                            {
                                "id": 1,
                                "name": "user_add",
                                "description": "add user",
                                "status": "A"
                            }
                        ]
                    }
                }
            },
            "notFound": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "message": {
                        "type": "string"
                    },
                    "httpCode": {
                        "type": "integer"
                    }
                },
                "example": {
                    "code": "GET_Role_FAILED",
                    "message": "Unable to get role failed",
                    "httpCode": 404
                }
            },
            "getEnterpriseDetails": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "enterpriseCode": {
                        "type": "string"
                    },
                    "admin": {
                        "type": "object",
                        "properties": {
                            "id": {
                                "type": "integer"
                            },
                            "username": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            },
                            "emailId": {
                                "type": "string"
                            },

                            "enterpriseCode": {
                                "type": "string"
                            },
                            "status": {
                                "type": "string"
                            },

                            "roleNames": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "permissionsNames": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "userType": {
                                "type": "integer"
                            }
                        }
                    },
                    "createdDate": {
                        "type": "string"
                    },
                    "lastUpdatedDate": {
                        "type": "string"
                    },
                    "defaultRoles": {
                        "type": "string"
                    },
                    "enterpriseType": {
                        "type": "integer"
                    }
                },
                "example": {
                    "name": "HM-org",
                    "status": "Active",
                    "enterpriseCode": "T16Z-4TAK-W5X7",
                    "admin": {
                        "id": 489,
                        "username": "HM-Org",
                        "name": "HM-org",
                        "emailId": "manjunath.hindupur@happiestminds.com",
                        "enterpriseCode": "T16Z-4TAK-W5X7",
                        "status": "A",
                        "roleNames": [
                            "PL Delete Model",
                            "PL User",
                            "PL Assessment Template Co-ordinator",
                            "Admin",
                            "PL Export Request",
                            "PL Assessment Approver"
                        ],
                        "permissionNames": [
                            "user_delete",
                            "resource_fetch",
                            "businessprocess_add",
                            "retentionrule_add",
                            "import_data",
                            "ia_approve"
                        ],
                        "userType": 1
                    },
                    "createDate": 1591803509000,
                    "lastUpdateDate": 1591803509000,
                    "defaultRoles": null,
                    "enterpriseType": 1
                }
            }
        }
    },
    "securitySchemes": {
        "api_key": {
            "type": "apiKey",
            "in": "header",
            "name": "Authorization"
        }
    }
}
